services:
  api:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: loyalty-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .docker/bin:/opt/docker/bin:cached
      - .:/var/www:cached
