
POST http://127.0.0.1:8000/api/account/create
Authorization: Bearer 1|2OxC6N8Xsrvhhk4NcJlQR8CrLud6IWgZC0bCkTkt
Accept: application/json
Content-Type: application/json

{
    "active": true,
    "card": 1234,
    "email": "ivan@example.com",
    "email_notification": true,
    "phone": "+79998887766",
    "phone_notification": true
}
