
POST http://127.0.0.1:8000/api/loyaltyPoints/withdraw
Authorization: Bearer 1|2OxC6N8Xsrvhhk4NcJlQR8CrLud6IWgZC0bCkTkt
Accept: application/json
Content-Type: application/json

{
    "account_id": 1,
    "account_type": "card",
    "description": "Тестирование",
    "points_amount": 1
}
